const actionTypes = {
  SWITCH_FILTER: 'SWITCH_FILTER',
  TOGGLE_TAB: 'TOGGLE_TAB',
  START_LOADING: 'START_LOADING',
  RECIVE_TICKETS: 'RECIVE_TICKETS',
  END_LOADING: 'END_LOADING',
  THROW_ERROR: 'THROW_ERROR',
  SHOW_MORE: 'SHOW_MORE',
};

export default actionTypes;
